# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


export HISTFILE=~/.zsh_history
export HISTSIZE=100000 # can't be unset, like in bash
export SAVEHIST=100000 # needed in order to save it somewhere
export CLICOLOR=1 # env variable

# Appends every command to the history file once it is executed
setopt inc_append_history
# Reloads the history whenever you use it
setopt share_history

# Keybindings, like the readline bindings
# We have VI key bindings! Screw emacs/readline :D Use insert/command mode
# http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html
# To get emacs key bindings, just do `bindkey -e`
# This is like `set -o vi` in bash, ref https://www.techrepublic.com/blog/linux-and-open-source/using-vi-key-bindings-in-bash-and-zsh/

# Re-use BASH aliases. Mostly compatible
BASH_D="$HOME/.bash.d"
BIN_DIR="$HOME/bin"

source ~/.bash.d/aliases_functions


if [[ ! -d ~/.zplug ]];then
  git clone https://github.com/zplug/zplug ~/.zplug
fi
source ~/.zplug/init.zsh
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/sudo", from:oh-my-zsh
zplug "plugins/command-not-found", from:oh-my-zsh
zplug "mafredri/zsh-async", from:github, defer:0 # Async for zsh, used by pure
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"
zplug "afreisinger/docker-alias", use:zshrc
zplug "rupa/z", use:z.sh
# Themes !
# zplug "themes/robbyrussell", from:oh-my-zsh, as:theme
  zplug "romkatv/powerlevel10k", as:theme, depth:1
# zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
# zplug "dracula/zsh", as:theme 

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
#zplug load --verbose
zplug load

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
